config/routes.rb
Rails.application.routes.draw do
 
  resources :books do
    resources :comments
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

http_basic_authenticate_with name: "gaya", password: "secret", except: [:index, :show]




  def new
    @book = Book.new
  end

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end


  def create
  @book = Book.new(book_params)
 
  if @book.save
  redirect_to @book
  else
    render 'new'
  end
end


  def update
  @book = Book.find(params[:id])
 
  if @book.update(book_params)
    redirect_to @book
  else
    render 'edit'
  end
end

def destroy
  @book = Book.find(params[:id])
  @book.destroy
 
  redirect_to books_path
end


  private
  def book_params
    params.require(:book).permit(:title, :author, :genre)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


http_basic_authenticate_with name: "gaya", password: "secret", only: :destroy



  def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.create(comment_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = @book.comments.find(params[:id])
    @comment.destroy
    redirect_to book_path(@book)
  end
  

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
 
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </p>

  <p>
    <%= f.label :genre %><br>
    <%= f.text_area :genre %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book-Info</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>My Book Shelf</h1>
 <h3><%= link_to 'Add New Book', new_book_path %></h3>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Genre</th>
    <th colspan="3"></th>
  </tr>
 
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.genre %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Delete', book_path(book),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <%#<%= link_to 'My Books', controller: 'books' %>
</table>

app/views/books/new.html.erb
<h1>Add New Book</h1>
<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
 
<p>
  <strong>Author:</strong>
  <%= @book.author %>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<h2>Comments</h2>
<%= render @book.comments %>


<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_book_path(@book) %>
<%= link_to 'Back', books_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.book, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@book, @book.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookHw</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>